name: C/C++ CI nicledomaS

on: [push]

jobs:
  ubuntu-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # , macOS-latest] # macOS fails because of SetupHunter - version not present altough first time build succeeded ???          

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON
